### PR TITLE
allow laravel 6 / 7

### PR DESCRIPTION
**Pull request by vv12131415**
- drop support for php < 7.3
- allow laravel 6 / 7
- update phpunit
- test against php 8

As you can see I have dropped versions, FYI this is still semver

### CODE REVIEW

**Comment by Germey** [comment]
Thanks for your contribution for supporting higher version of Laravel.
You can operate the Merge Operation.
Thanks!

**Review by Germey — APPROVED** [review]

**Comment by vladyslavstartsev** [comment]
image

@Germey as you can see, I have no "merge button".

Can you help me with this?

**Comment by Germey** [comment]
Merged

**Comment by vv12131415** [comment]
@Germey thanks a lot!

**Comment by Germey** [comment]
I’ve send the new invitation of repo again, please accept, thanks so much.

**Pull request merged**
